name: Build and Test Assembly Code

on: [push, pull_request]

jobs:
  build:
    runs-on: macos-15

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: run
        run: |
          make run
